---
- name: Deploy master
  hosts: L2-kect
  gather_facts: false
  # run_once: true
  vars:
    tmp_dir: /root/tmp
    dpy_dir: "{{tmp_dir}}/{{cluster_name}}"
  tasks:
  - include_role:
      name: master

