---
- name: Prepare ssl on local machine
  hosts: L2-kect
  connection: local
  become: false
  gather_facts: false
  run_once: true
  vars:
    tmp_dir: /root/tmp
    dpy_dir: "{{tmp_dir}}/{{cluster_name}}"
  tasks:
  - name: "check cluster name"
    fail:
      msg: "NO cluster_name"
    when: not  cluster_name


  - include_role:
       name: local

