---
- name: generate  calico rbac
  template:
    src: calico_rbac.yml.j2
    dest: "{{mnf_dir}}/calico_rbac.yml"

- name: generate  calico component
  template:
    src: calico_component.yml.j2
    dest: "{{mnf_dir}}/calico_component.yml"