---

- name: "create pki_dir" 
  file: path="{{dpy_pki_dir}}" state=directory mode=0755

- name: "create kcf_dir" 
  file: path="{{dpy_kcf_dir}}" state=directory mode=0755

- name: "create mnf_dir" 
  file: path="{{dpy_mnf_dir}}" state=directory mode=0755

- name: "create kom_dir" 
  file: path="{{dpy_kom_dir}}" state=directory mode=0755

- name: generate crt
  import_tasks: pki.yml

- name: generate kubelet of master bootstrap manifest
  import_tasks: kom_bootstrap.yml

- name: generate etcd manifest
  import_tasks: etcd.yml
  vars:
    etcd_peer: "{{ansible_play_hosts}}"

- name: generate control plane manifest
  import_tasks: control_plane.yml
  vars:
    etcd_peer: "{{ansible_play_hosts}}"

- name: generate node bootstrap manifest
  import_tasks: bootstrap.yml

- name: generate calico manifest
  import_tasks: calico.yml
  vars:
    etcd_peer: "{{ansible_play_hosts}}"

- name: generate kube-proxy manifest
  import_tasks: proxy.yml

- name: generate coredns manifest
  import_tasks: coredns.yml