---
- name: Generate openssl conf
  template: 
    src: openssl.cnf.j2
    dest: "{{dpy_pki_dir}}/openssl.cnf"

- name: Generate ca certificates
  shell: "{{item}}"
  args:
    chdir: "{{dpy_pki_dir}}"
  with_items:
    - openssl ecparam -name secp521r1 -genkey -noout -out {{root_key}}
    - openssl req -x509 -new -sha256 -nodes -key {{root_key}} -days 3650 -out {{root_crt}} -subj "/CN=k8s-{{cluster_name}}-ca"  -extensions v3_ca -config ./openssl.cnf


- name: Generate apiserver certificates
  shell: "{{item}}"
  args:
    chdir: "{{dpy_pki_dir}}"
  with_items:
    - openssl ecparam -name secp521r1 -genkey -noout -out {{api_key}}
    - openssl req -new -sha256 -key {{api_key}} -subj "/CN=k8s-{{cluster_name}}-apiserver" | openssl x509 -req -sha256 -CA {{root_crt}} -CAkey {{root_key}} -CAcreateserial  
          -out {{api_crt}} -days 365 -extensions v3_apiserver -extfile ./openssl.cnf

- name: Generate admin certificates
  shell: "{{item}}"
  args:
    chdir: "{{dpy_pki_dir}}"
  with_items:
    - openssl ecparam -name secp521r1 -genkey -noout -out {{admin_key}}
    - openssl req -new -key {{admin_key}} -subj "/CN=k8s-{{cluster_name}}-admin/O=system:masters" | openssl x509 -req -sha256 -CA {{root_crt}} -CAkey {{root_key}} -CAcreateserial 
          -out {{admin_crt}} -days 365 -extensions v3_client -extfile ./openssl.cnf

- name: Generate service account certificates
  shell: "{{item}}"
  args:
    chdir: "{{dpy_pki_dir}}"
  with_items:
    - openssl ecparam -name secp521r1 -genkey -noout -out {{sa_key}}
    - openssl ec -in {{sa_key}} -outform PEM -pubout -out {{sa_pub}}


- name: Generate kubelet-client certificates
  shell: "{{item}}"
  args:
    chdir: "{{dpy_pki_dir}}"
  with_items:
    - openssl ecparam -name secp521r1 -genkey -noout -out {{kubelet_client_key}}
    - openssl req -new -key {{kubelet_client_key}} -subj "/CN=k8s-{{cluster_name}}-kubelet-client/O=system:masters" | openssl x509 -req -sha256 -CA {{root_crt}} -CAkey {{root_key}} -CAcreateserial 
          -out {{kubelet_client_crt}} -days 365 -extensions v3_client -extfile ./openssl.cnf

- name: Generate kube-proxy certificates
  shell: "{{item}}"
  args:
    chdir: "{{dpy_pki_dir}}"
  with_items:
    - openssl ecparam -name secp521r1 -genkey -noout -out {{proxy_key}}
    - openssl req -new -sha256 -key {{proxy_key}} -subj "/CN=system:kube-proxy" | openssl x509 -req -sha256 -CA {{root_crt}} -CAkey {{root_key}} -CAcreateserial 
          -out {{proxy_crt}} -days 365 -extensions v3_client -extfile ./openssl.cnf