---
- file: path="{{k8s_hostdir}}" state=absent

- file: path="{{item}}" state=directory mode=0755
  with_items:
    - "{{k8s_etc_hostdir}}"
    - "{{k8s_pki_hostdir}}"

- name: clean iptables
  shell: "{{item}}"
  with_items:
  - iptables -F
  - iptables -X
  - iptables -t nat -F
  - iptables -t nat -X

- file: path="{{item}}" state=directory mode=0755
  with_items:
    - "{{cni_bin_dir}}"
    - "{{cni_etc_dir}}"

- name: config kubelet bootstrap kubeconfig
  copy:
    src: "{{dpy_kcf_dir}}/{{bsp_kcf}}"
    dest: "{{k8s_etc_hostdir}}/{{bsp_kcf}}"

- name: config kubelet.service
  template:
    src: kubelet.service.j2
    dest: /usr/lib/systemd/system/kubelet.service

- name: start kubelet
  systemd:
    name: kubelet
    state: restarted
    daemon_reload: yes