---

- unarchive:
    src: "{{kernel_tar}}"
    dest: /tmp

- shell: cd /tmp/{{kernel_dir}} && ./install.sh

# - shell: yum update -y

- name: Reboot server
  shell: sleep 1 && systemctl reboot
  async: 1
  poll: 0

- name: Wait for the server to finish rebooting
  sudo: no
  local_action: wait_for host="{{ inventory_hostname }}" search_regex=OpenSSH port=22 timeout=400