---
- file: path="{{kom_hostdir}}" state=absent

- file: path="{{item}}" state=directory mode=0755
  with_items:
    - "{{kom_etc_hostdir}}"
    - "{{kom_pki_hostdir}}"
  
- name: clean iptables
  shell: "{{item}}"
  with_items:
  - iptables -F
  - iptables -X
  - iptables -t nat -F
  - iptables -t nat -X


- name: copy kubelet of master bootstrap kubeconfig
  copy:
    src: "{{dpy_kom_dir}}/{{bsp_kcf}}"
    dest: "{{kom_etc_hostdir}}/{{bsp_kcf}}"

- name: config kubelet.service
  template:
    src: kubelet_of_master.service.j2
    dest: /usr/lib/systemd/system/kubelet.service

- name: start kubelet
  systemd:
    name: kubelet
    state: restarted
    daemon_reload: yes