---
- file: path="{{A_kom_hostdir}}" state=absent

- file: path="{{item}}" state=directory mode=0755
  with_items:
    - "{{A_kom_etc_hostdir}}"
    - "{{A_kom_pki_hostdir}}"
  

- name: copy kubelet of master bootstrap kubeconfig
  copy:
    src: "{{dpy_kom_dir}}/{{AA_bsp_kcf}}"
    dest: "{{A_kom_etc_hostdir}}/{{AA_bsp_kcf}}"

- name: config kubelet.service
  template:
    src: kubelet_of_master.service.j2
    dest: /usr/lib/systemd/system/kubelet.service

- name: start kubelet
  systemd:
    name: kubelet
    state: restarted
    daemon_reload: yes