---
- file: path="{{k8s_hostdir}}" state=absent

- file: path="{{item}}" state=directory mode=0755
  with_items:
    - "{{k8s_etc_hostdir}}"
    - "{{k8s_pki_hostdir}}"


- name: copy pki file
  copy:
    src: "{{dpy_pki_dir}}/{{item}}"
    dest: "{{k8s_pki_hostdir}}"
  with_items:
  - "{{root_crt}}"
  - "{{root_key}}"
  - "{{api_crt}}"
  - "{{api_key}}"
  - "{{sa_pub}}"
  - "{{sa_key}}"
  - "{{kubelet_client_crt}}"
  - "{{kubelet_client_key}}"

- name: copy kcf file
  copy:
    src: "{{dpy_kcf_dir}}/{{item}}"
    dest: "{{k8s_etc_hostdir}}"
  with_items:
  - "{{cm_kcf}}"
  - "{{sch_kcf}}"