kube_img: uhub.service.ucloud.cn/wxyz/hyperkube:v1.8.5
infra_img: "uhub.service.ucloud.cn/wxyz/gc-pause-amd64:3.0"
etcd_img: "uhub.service.ucloud.cn/wxyz/coreos-etcd"
calico_control_img: "uhub.service.ucloud.cn/wxyz/calico-kube-controllers:v2.0.0"
calico_node_img: "uhub.service.ucloud.cn/wxyz/calico-node:v3.0.1"
calico_cni_img: "uhub.service.ucloud.cn/wxyz/calico-cni:v2.0.0"
coredns_img: "uhub.service.ucloud.cn/wxyz/coredns:1.0.2"

# ### folder
# k8s_etc_dir: /etc/k8s
# k8s_pki_dir: "{{k8s_etc_dir}}/pki"
# k8s_etc_dir_host: /etc/k8s
# k8s_pki_dir_host: "{{k8s_etc_dir_host}}/pki"

# ### cert
# sa_key: "{{k8s_pki_dir}}/sa.pub"
# sa_pri_key: "{{k8s_pki_dir}}/sa.key"
# client_ca: "{{k8s_pki_dir}}/ca.crt"
# kubelet_client_crt: "{{k8s_pki_dir}}/kubelet-client.crt"
# kubelet_client_key: "{{k8s_pki_dir}}/kubelet-client.key"
# tls_crt: "{{k8s_pki_dir}}/apiserver.crt"
# tls_key: "{{k8s_pki_dir}}/apiserver.key"
# cluster_signing_crt: "{{k8s_pki_dir}}/ca.crt"
# cluster_signing_key: "{{k8s_pki_dir}}/ca.key"
# root_ca: "{{k8s_pki_dir}}/ca.crt"

# ### kcf
# cm_kcf: "{{k8s_etc_dir}}/cm.kcf"
# sch_kcf: "{{k8s_etc_dir}}/sch.kcf"
# bsp_kcf: "{{k8s_etc_dir}}/bootstrap.kcf"
# proxy_kcf: "{{k8s_etc_dir}}/proxy.kcf"

### cni
cni_dir: "/opt/cni"
cni_bin_dir: "{{cni_dir}}/bin"
cni_etc_dir: "{{cni_dir}}/etc"

cni_hostdir: "/opt/cni"
cni_bin_hostdir: "{{cni_hostdir}}/bin"
cni_etc_hostdir: "{{cni_hostdir}}/etc"

### k8s
A_k8s_dir: "/etc/k8s"
A_k8s_etc_dir: "{{A_k8s_dir}}"
A_k8s_pki_dir: "{{A_k8s_dir}}/pki"

A_k8s_hostdir: "/opt/k8s"
A_k8s_etc_hostdir: "{{A_k8s_hostdir}}"
A_k8s_pki_hostdir: "{{A_k8s_hostdir}}/pki"

A_kom_hostdir: "/opt/kom"
A_kom_etc_hostdir: "{{A_kom_hostdir}}"
A_kom_pki_hostdir: "{{A_kom_hostdir}}/pki"


### deploy
dpy_pki_dir: "{{dpy_dir}}/pki"
dpy_mnf_dir: "{{dpy_dir}}/mnf"
dpy_kcf_dir: "{{dpy_dir}}/kcf"
dpy_kom_dir: "{{dpy_dir}}/kom"

### cert
AA_root_crt: "ca.crt"
AA_root_key: "ca.key"
AA_api_crt: "apiserver.crt"
AA_api_key: "apiserver.key"
AA_admin_crt: "admin.crt"
AA_admin_key: "admin.key"
# AA_sa_crt: "sa.crt"
AA_sa_pub: "sa.pub"
AA_sa_key: "sa.key"
AA_kubelet_client_crt: "kubelet-client.crt"
AA_kubelet_client_key: "kubelet-client.key"
AA_proxy_crt: "proxy.crt"
AA_proxy_key: "proxy.key"

AA_client_ca: "{{AA_root_crt}}"
AA_cluster_signing_crt: "{{AA_root_crt}}"
AA_cluster_signing_key: "{{AA_root_key}}"


### kcf
AA_cm_kcf: "cm.kcf"
AA_sch_kcf: "sch.kcf"
AA_bsp_kcf: "bootstrap.kcf"
AA_admin_kcf: "admin.kcf"
AA_proxy_kcf: "proxy.kcf"

AA_kube_kcf: "kubeconfig"

AA_kom_bsp_kcf: "kom_bsp.kcf"


### mnf
AA_etcd_mnf: "etcd.yml"
AA_cnp_mnf: "control_plane.yml"
AA_bsp_mnf: "bootstrap_token.yml"
AA_bsp_rbac_mnf: "bootstrap_rbac.yml"
AA_clc_mnf: "calico_component.yml"
AA_clc_rbac_mnf: "calico_rbac.yml"
AA_proxy_mnf: "proxy.yml"
AA_cds_mnf: "coredns.yml"

AA_kom_bsp_mnf: "kom_bootstrap_token.yml"

