kube_img: uhub.service.ucloud.cn/wxyz/hyperkube:v1.8.5
infra_img: "uhub.service.ucloud.cn/wxyz/gc-pause-amd64:3.0"
etcd_img: "uhub.service.ucloud.cn/wxyz/coreos-etcd"
calico_control_img: "uhub.service.ucloud.cn/wxyz/calico-kube-controllers:v2.0.0"
calico_node_img: "uhub.service.ucloud.cn/wxyz/calico-node:v3.0.1"
calico_cni_img: "uhub.service.ucloud.cn/wxyz/calico-cni:v2.0.0"
coredns_img: "uhub.service.ucloud.cn/wxyz/coredns:1.0.2"

# ### folder
# k8s_etc_dir: /etc/k8s
# k8s_pki_dir: "{{k8s_etc_dir}}/pki"
# k8s_etc_dir_host: /etc/k8s
# k8s_pki_dir_host: "{{k8s_etc_dir_host}}/pki"

# ### cert
# sa_key: "{{k8s_pki_dir}}/sa.pub"
# sa_pri_key: "{{k8s_pki_dir}}/sa.key"
# client_ca: "{{k8s_pki_dir}}/ca.crt"
# kubelet_client_crt: "{{k8s_pki_dir}}/kubelet-client.crt"
# kubelet_client_key: "{{k8s_pki_dir}}/kubelet-client.key"
# tls_crt: "{{k8s_pki_dir}}/apiserver.crt"
# tls_key: "{{k8s_pki_dir}}/apiserver.key"
# cluster_signing_crt: "{{k8s_pki_dir}}/ca.crt"
# cluster_signing_key: "{{k8s_pki_dir}}/ca.key"
# root_ca: "{{k8s_pki_dir}}/ca.crt"

# ### kcf
# cm_kcf: "{{k8s_etc_dir}}/cm.kcf"
# sch_kcf: "{{k8s_etc_dir}}/sch.kcf"
# bsp_kcf: "{{k8s_etc_dir}}/bootstrap.kcf"
# proxy_kcf: "{{k8s_etc_dir}}/proxy.kcf"

### cni
cni_dir: "/opt/cni"
cni_bin_dir: "{{cni_dir}}/bin"
cni_etc_dir: "{{cni_dir}}/etc"

cni_hostdir: "/opt/cni"
cni_bin_hostdir: "{{cni_hostdir}}/bin"
cni_etc_hostdir: "{{cni_hostdir}}/etc"

### k8s
k8s_dir: "/etc/k8s"
k8s_etc_dir: "{{k8s_dir}}"
k8s_pki_dir: "{{k8s_dir}}/pki"

k8s_hostdir: "/opt/k8s"
k8s_etc_hostdir: "{{k8s_hostdir}}"
k8s_pki_hostdir: "{{k8s_hostdir}}/pki"

kom_hostdir: "/opt/kom"
kom_etc_hostdir: "{{kom_hostdir}}"
kom_pki_hostdir: "{{kom_hostdir}}/pki"


### deploy
dpy_pki_dir: "{{dpy_dir}}/pki"
dpy_mnf_dir: "{{dpy_dir}}/mnf"
dpy_kcf_dir: "{{dpy_dir}}/kcf"
dpy_kom_dir: "{{dpy_dir}}/kom"

### cert
root_crt: "ca.crt"
root_key: "ca.key"
api_crt: "apiserver.crt"
api_key: "apiserver.key"
admin_crt: "admin.crt"
admin_key: "admin.key"
# sa_crt: "sa.crt"
sa_pub: "sa.pub"
sa_key: "sa.key"
kubelet_client_crt: "kubelet-client.crt"
kubelet_client_key: "kubelet-client.key"
proxy_crt: "proxy.crt"
proxy_key: "proxy.key"

client_ca: "{{root_crt}}"
cluster_signing_crt: "{{root_crt}}"
cluster_signing_key: "{{root_key}}"


### kcf
cm_kcf: "cm.kcf"
sch_kcf: "sch.kcf"
bsp_kcf: "bootstrap.kcf"
admin_kcf: "admin.kcf"
proxy_kcf: "proxy.kcf"

kube_kcf: "kubeconfig"

kom_bsp_kcf: "kom_bsp.kcf"


### mnf
etcd_mnf: "etcd.yml"
cnp_mnf: "control_plane.yml"
bsp_mnf: "bootstrap_token.yml"
bsp_rbac_mnf: "bootstrap_rbac.yml"
clc_mnf: "calico_component.yml"
clc_rbac_mnf: "calico_rbac.yml"
proxy_mnf: "proxy.yml"
cds_mnf: "coredns.yml"

kom_bsp_mnf: "kom_bootstrap_token.yml"

